# Generated by Django 4.2.7 on 2023-11-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_distillery_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='distillery',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
