# Generated by Django 4.2.7 on 2023-11-15 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_distillery_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whiskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rating', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Meh'), (4, 'Bad'), (5, 'Budweiser')], default=3)),
                ('notes', models.TextField()),
                ('distillery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiskey_distillery', to='home.distillery')),
            ],
        ),
    ]
